### ISSUE TITLE
chrome edge 翻译弹窗无法关闭

### ISSUE THREAD

**Issue by gongwannan** [Kobshobe/qy_translate#11]
![image](https://user-images.githubusercontent.com/48170648/212785775-97227df5-5caa-4d9b-a18b-b605db0978bb.png)
chrome 后续会移除 event 的 path 代码执行报错
https://chromestatus.com/feature/5726124632965120

**Comment by enzanumo** [comment]
同样的问题。

**Comment by Kobshobe** [comment]
已修复
