### ISSUE TITLE
建议在固定在桌面的图标右侧增加一个关闭按钮

### ISSUE THREAD

**Issue by passanywhere** [Kobshobe/qy_translate#13]
如题，建议在弹出的翻译页面框右侧增加一个关闭按钮。
弹框没有关闭按钮，一旦弹出后，就会遮挡住弹框背后的网页内容，还无法关闭（必须重新刷新网页后，弹框才会消失）
这样不方便[阅读，比较影响用户体验。
![qy_tr](https://user-images.githubusercontent.com/44995918/218051975-a3f23c70-7085-432f-86c6-04081bfa9cd4.png)

**Comment by Kobshobe** [comment]
bug引起，已修复，更新到最新版本即可
