### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by devunion** [Kobshobe/qy_translate#2]
I got latest version from master and tried to build it. But in the process of build I'm getting the next errors:

 error  in ./node_modules/element-plus/packages/theme-chalk/src/button.scss

SassError: Invalid CSS after "$--colors: map": expected expression (e.g. 1px, bold), was ".deep-merge("
        on line 17 of node_modules/element-plus/packages/theme-chalk/src/common/var.scss
        from line 3 of node_modules/element-plus/packages/theme-chalk/src/button.scss
>> $--colors: map.deep-merge(

   --------------^

**Comment by Kobshobe** [comment]
I have update dependencies
