### ISSUE TITLE
扩展程序CSS污染正常页面样式

### ISSUE THREAD

**Issue by 0xDarker** [Kobshobe/qy_translate#3]
扩展程序页面的CSS污染到了正常的页面样式，希望加上一个全局CSS命名空间避免污染
![image](https://user-images.githubusercontent.com/13844947/148494675-51fd84d5-2746-4ba7-86ad-cd7cc362e38b.png)

**Comment by bwcxyk** [comment]
+1

**Comment by Mr-Pro** [comment]
https://element.eleme.cn/#/zh-CN/component/button
element 样式被污染，导致按钮文字不居中偏下
