### ISSUE TITLE
请问在哪下载crx文件版本？

### ISSUE THREAD

**Issue by paroc108** [Kobshobe/qy_translate#6]
请问在哪下载crx文件版本？

**Comment by yafovo** [comment]
无法打开Chrome应用高店？
用edge下载，自己打包一下（但是我用1.7.1版本打包后，加载到chrome，会因安全问题无法启用）。
或者
直接在edge下载拓展，然后打开chrome，点 加载已解压的拓展，选择edge拓展目录下的拓展，就能使用拓展了。
具体目录百度一下很好找，缺点是以后拓展更新，得自己手动指定目录。
